#!/bin/bash

# SOURCE has been generated by running ls -lhR (being positionned in HOME directory)
SOURCE=w_nas.ls
TARGET=dirsizes.ls
DIRLIST=$(grep  '\:$' ${SOURCE}  | sed 's/://' | sed 's/ /:/g')

for i in  ${DIRLIST};
do 
	echo -n "${i} "
	ls ${HOME}/"${i//:/ }" | wc -w 
done > ${TARGET}
dirsizes.ls